trigger: 
  branches: 
    include: 
      - main 
pool: 
  name: AEM Agent Pool
 
steps:

- task: MavenAuthenticate@0 
  displayName: 'Maven Authenticate' 
  inputs: 
    artifactsFeeds: 'test-feed'

- task: Bash@3
  inputs:
    targetType: 'inline'
    script: 'echo "##vso[task.setvariable variable=NODE_EXTRA_CA_CERTS;]/data/certs/sonarcentral-uat.indusind.pem"'
- task: SonarQubePrepare@5
  inputs:
    SonarQube: 'Indus-Sonar-Conn'
    scannerMode: 'Other'
    extraProperties: |
      # Additional properties that will be passed to the scanner,
      # Put one key=value per line, example:
      # sonar.exclusions=**/*.bin
      sonar.projectKey=AEM-Website_IndusInd_microsite_latest_AYpMAKTL6xC0bfamOz0E

- task: Maven@4
  inputs:
    mavenPomFile: 'pom.xml'
    goals: 'install'
    publishJUnitResults: true
    testResultsFiles: '**/surefire-reports/TEST-*.xml'
    javaHomeOption: 'JDKVersion'
    mavenVersionOption: 'Default'
    mavenAuthenticateFeed: false
    effectivePomSkip: false
    sonarQubeRunAnalysis: false
- script: |
    export JAVA_HOME=/usr/lib/jvm/java-11-openjdk-11.0.20.0.8-3.el8.x86_64
    export PATH=$JAVA_HOME/bin:$PATH
    mvn sonar:sonar
  displayName: 'Analyze with mvn sonar'


- task: CopyFiles@2
  inputs:
    SourceFolder: '$(System.DefaultWorkingDirectory)'
    Contents: '**/target/*.jar'
    TargetFolder: '$(Build.ArtifactStagingDirectory)'

- task: PublishPipelineArtifact@1
  inputs:
    targetPath: '$(Build.ArtifactStagingDirectory)'
    artifactName: $(artifactName)